# Generated by Django 5.2.1 on 2025-10-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0007_serviceorder_company_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderitem',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alinhamento'), (2, 'Aperto de tirantes'), (3, 'Borracharia'), (4, 'Socorro'), (5, 'Balanceamento'), (6, 'Destravamento de tirante'), (7, 'Destravamento de barra'), (8, 'Consultoria técnica'), (9, 'Troca de pivô'), (10, 'Desempeno de barra')]),
        ),
    ]
