# Generated by Django 5.2.1 on 2025-10-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0008_alter_serviceorderitem_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertruck',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='serviceordertruck',
            name='observation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da observação'),
        ),
    ]
