# Generated by Django 5.2.1 on 2025-10-12 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0013_clear_existing_service_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertruck',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
