# Generated by Django 5.2.1 on 2025-10-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0014_serviceordertruck_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceordertruck',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Placa'),
        ),
    ]
