# Generated by Django 5.2.1 on 2025-10-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0015_alter_serviceordertruck_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='vehicle_plate',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Placa do veículo'),
        ),
        migrations.AlterField(
            model_name='serviceordertruck',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Placa'),
        ),
    ]
