# Generated by Django 5.2.1 on 2025-05-10 11:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=60)),
                ('axle_count', models.PositiveSmallIntegerField()),
                ('tire_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['axle_count', 'tire_count'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='Contato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('hodometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hodômetro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='core.company')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.trucktype')),
            ],
            options={
                'ordering': ['plate'],
                'unique_together': {('company', 'plate')},
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hodômetro')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.truck')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('groove_1', models.CharField(blank=True, max_length=10, verbose_name='Sulco 1')),
                ('groove_2', models.CharField(blank=True, max_length=10, verbose_name='Sulco 2')),
                ('groove_3', models.CharField(blank=True, max_length=10, verbose_name='Sulco 3')),
                ('groove_4', models.CharField(blank=True, max_length=10, verbose_name='Sulco 4')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='Marca')),
                ('pattern', models.CharField(blank=True, max_length=30, verbose_name='Desenho')),
                ('fire_number', models.CharField(blank=True, max_length=20, verbose_name='Nº Fogo')),
                ('dot', models.CharField(blank=True, max_length=15, verbose_name='DOT')),
                ('rec', models.BooleanField(default=False, verbose_name='Recapado')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='core.inspection')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('inspection', 'position')},
            },
        ),
    ]
