# Generated by Django 5.1 on 2025-04-30 01:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trucktype_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hodômetro')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.truck')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('groove_1', models.CharField(blank=True, max_length=10, verbose_name='Sulco 1')),
                ('groove_2', models.CharField(blank=True, max_length=10, verbose_name='Sulco 2')),
                ('groove_3', models.CharField(blank=True, max_length=10, verbose_name='Sulco 3')),
                ('groove_4', models.CharField(blank=True, max_length=10, verbose_name='Sulco 4')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='Marca')),
                ('pattern', models.CharField(blank=True, max_length=30, verbose_name='Desenho')),
                ('fire_number', models.CharField(blank=True, max_length=20, verbose_name='Nº Fogo')),
                ('dot', models.CharField(blank=True, max_length=15, verbose_name='DOT')),
                ('rec', models.CharField(blank=True, max_length=15, verbose_name='Rec')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='core.inspection')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('inspection', 'position')},
            },
        ),
    ]
