# Generated by Django 5.2.1 on 2025-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inspection_tire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='rec',
            field=models.BooleanField(default=False, verbose_name='Recapado'),
        ),
    ]
