# Generated by Django 5.2.1 on 2025-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_trucktype_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucktype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
