# Generated by Django 5.2.1 on 2025-05-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_code_length'),
        ('core', '0005_trucktype_initial_data'),
    ]

    operations = [
    ]
