# Generated by Django 5.2.1 on 2025-07-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250510_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='groove_4',
        ),
    ]
