# Generated by Django 5.2.1 on 2025-07-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tire_groove_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='groove_4',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sulco 4'),
        ),
    ]
