# Generated by Django 5.2.1 on 2025-07-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tire_groove_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='groove_4',
        ),
        migrations.AlterField(
            model_name='tire',
            name='groove_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sulco D'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='groove_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sulco M'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='groove_3',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sulco F'),
        ),
    ]
